Descomentado linhas para remover pacotes no Root-remove e acrescetado arquivo Root-remove no gnome

diff --git a/.github/workflows/make-profiles.yml b/.github/workflows/make-profiles.yml
--- a/.github/workflows/make-profiles.yml
+++ b/.github/workflows/make-profiles.yml
@@ -115,12 +115,12 @@ jobs:
                 rsync -Cravzp --delete shared/ biglinux/$i
                 
                 # # Remove Desktop
-                # if [ -e "$makeisoprofilesdir/$i/Desktop-remove" ]; then
-                #     grep -v -f $makeisoprofilesdir/$i/Desktop-remove  $manjaroProfiles/shared/Packages-Desktop  >  biglinux/$i/Packages-Desktop
-                # else
-                #    echo "ERROR Remove Desktop $i"
-                #    exit 1
-                # fi
+                if [ -e "$makeisoprofilesdir/$i/Desktop-remove" ]; then
+                    grep -v -f $makeisoprofilesdir/$i/Desktop-remove  $manjaroProfiles/shared/Packages-Desktop  >  biglinux/$i/Packages-Desktop
+                else
+                   echo "ERROR Remove Desktop $i"
+                   exit 1
+                fi
                 
                 # Add Desktop
                 if [ -e "$makeisoprofilesdir/$i/Desktop-add" ]; then
